server.port=8080

# URLs de los microservicios destino
gateway.services.auth=http://localhost:8081
gateway.services.comercio=http://localhost:8082
gateway.services.pedido=http://localhost:8083

# Calibración de servidor para alta concurrencia
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20
server.tomcat.connection-timeout=20000
